//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int odr_id { get; set; }
        public Nullable<int> prd_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
